In [1]:
import numpy as np

In [2]:
np.__version__

'2.3.3'

## Create & Read

#### 1D Array

In [3]:
arr1 = np.array([1, 2, 3, 4, 5])
arr1

array([1, 2, 3, 4, 5])

In [4]:
type(arr1)

numpy.ndarray

In [5]:
arr1.shape

(5,)

In [6]:
arr1.dtype

dtype('int64')

In [7]:
arr1.ndim

1

#### 2D Array

In [8]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [9]:
arr2.ndim

2

In [10]:
arr2.shape

(2, 3)

In [11]:
arr2.dtype

dtype('int64')

#### 3D Array

In [12]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [13]:
arr3.ndim

3

In [14]:
arr3.shape

(3, 2, 3)

### Create Random Array

In [15]:
rand_array = np.random.rand(3, 2, 3)
rand_array

array([[[0.81350005, 0.65803314, 0.99482531],
        [0.10499961, 0.57940257, 0.22227359]],

       [[0.662888  , 0.15029386, 0.08047852],
        [0.52905546, 0.68483427, 0.55982458]],

       [[0.24058673, 0.83438611, 0.88050259],
        [0.84775607, 0.73733712, 0.59092456]]])

In [16]:
rand_array.dtype

dtype('float64')

In [17]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [18]:
zeroes.ndim

3

In [19]:
full = np.full((3, 2, 3), 8)
full

array([[[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]],

       [[8, 8, 8],
        [8, 8, 8]]])

In [20]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [21]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

### Update & Delete

In [22]:
a1 = np.random.rand(2, 3, 2)
a2 = np.random.rand(2, 3, 2)

In [23]:
a1

array([[[0.9138506 , 0.82935438],
        [0.76105974, 0.95138323],
        [0.97886825, 0.36155767]],

       [[0.4275764 , 0.03919583],
        [0.24351767, 0.82664376],
        [0.45884548, 0.19837438]]])

In [24]:
a2

array([[[0.39243684, 0.18376313],
        [0.51218111, 0.55750874],
        [0.83381794, 0.62641716]],

       [[0.72611104, 0.73938751],
        [0.39975919, 0.68081329],
        [0.54722164, 0.80015229]]])

### Basic Math Operations

In [25]:
np.add(a1, a2)

array([[[1.30628744, 1.01311751],
        [1.27324086, 1.50889197],
        [1.81268619, 0.98797483]],

       [[1.15368744, 0.77858334],
        [0.64327687, 1.50745706],
        [1.00606713, 0.99852667]]])

In [26]:
np.subtract(a1, a2)

array([[[ 0.52141376,  0.64559125],
        [ 0.24887863,  0.39387449],
        [ 0.1450503 , -0.26485949]],

       [[-0.29853464, -0.70019167],
        [-0.15624152,  0.14583047],
        [-0.08837616, -0.60177791]]])

In [27]:
np.divide(a1, a2)

array([[[2.32865648, 4.51317069],
        [1.48591919, 1.70649026],
        [1.1739592 , 0.57718353]],

       [[0.58885815, 0.05301122],
        [0.60916091, 1.21420039],
        [0.83850025, 0.24792078]]])

In [28]:
np.divide(ones, zeroes)

C:\Users\ilian\AppData\Local\Temp\ipykernel_9556\3074862441.py:1: RuntimeWarning: divide by zero encountered in divide
  np.divide(ones, zeroes)


array([[[inf, inf, inf],
        [inf, inf, inf]],

       [[inf, inf, inf],
        [inf, inf, inf]],

       [[inf, inf, inf],
        [inf, inf, inf]]])

In [29]:
np.multiply(a1, a2)

array([[[0.35862865, 0.15240476],
        [0.38980043, 0.53040446],
        [0.81619791, 0.22648593]],

       [[0.31046794, 0.02898091],
        [0.09734843, 0.56279006],
        [0.25109018, 0.15872971]]])

### Statistical Operations

In [30]:
sqrt = np.sqrt(25)
absolute = np.abs(-2)
power = np.pow(2, 8)
log = np.log(25)
mins = np.min(a1)
maxs = np.max(a2)

In [31]:
sqrt

np.float64(5.0)

In [32]:
absolute

np.int64(2)

In [33]:
power

np.int64(256)

In [34]:
log

np.float64(3.2188758248682006)

In [35]:
mins

np.float64(0.03919583389170589)

In [36]:
maxs

np.float64(0.8338179448536105)

In [37]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

### Appending & Inserting

In [38]:
new_arr = np.ones((3, 2, 3))

In [39]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [40]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [41]:
appd = np.append(zeroes, new_arr, axis=0)
appd

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [43]:
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [44]:
new_arr

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [45]:
inserted_arr = np.insert(zeroes, 1, new_arr, axis=0)
inserted_arr

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

### Delete

In [46]:
arr4 = np.random.rand(3, 2, 3)
arr4

array([[[0.12831783, 0.27319958, 0.97955542],
        [0.58535116, 0.93282421, 0.56630437]],

       [[0.86333104, 0.19421167, 0.64643042],
        [0.70006968, 0.49637116, 0.12390956]],

       [[0.84997907, 0.90429345, 0.40227594],
        [0.29760571, 0.1406886 , 0.78599363]]])

In [48]:
arr5 = np.delete(arr4, 0, axis=1)

In [49]:
arr5

array([[[0.58535116, 0.93282421, 0.56630437]],

       [[0.70006968, 0.49637116, 0.12390956]],

       [[0.29760571, 0.1406886 , 0.78599363]]])

In [50]:
np.save("new_array", arr5)